### ISSUE TITLE
Possible config overrite in ~/.bashrc

### ISSUE THREAD

**Issue by IOAyman** [SamyMe/vimrc#1]
You probably should use a double greater-than sign to append the alias to `~/.bashrc`.  Any previous configuration you had there would be overwritten if you use only one.

``` bash
echo "alias vi='vimx'" >> ~/.bashrc
```

**Comment by SamyMe** [comment]
Of course,  you're totally right.  I still need to recheck those lines to make the script runable on my debian-based and redhat-based systems.
